const data = {
  products: [
    {
      _id: "1",
      name: "Louis Vuitton Dress",
      category: "Dress",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Louis Vuitton",
      rating: 4.5,
      numReview: 10,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "Gucci Dress",
      category: "Dress",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Gucci",
      rating: 4,
      numReview: 20,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Dior Dress",
      category: "Dress",
      image: "/images/p3.jpg",
      price: 150,
      countInStock: 5,
      brand: "Dior",
      rating: 4.5,
      numReview: 15,
      description: "High Quality Product",
    },
    {
      _id: "4",
      name: "Chanel Dress",
      category: "Dress",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 15,
      brand: "Chanel",
      rating: 4.5,
      numReview: 9,
      description: "High Quality Product",
    },
    {
      _id: "5",
      name: "Prada Dress",
      category: "Dress",
      image: "/images/p5.jpg",
      price: 170,
      countInStock: 0,
      brand: "H&M",
      rating: 4.5,
      numReview: 15,
      description: "High Quality Product",
    },
    {
      _id: "6",
      name: "Celine Dress",
      category: "Dress",
      image: "/images/p6.jpg",
      price: 180,
      countInStock: 15,
      brand: "Celine",
      rating: 5.0,
      numReview: 25,
      description: "High Quality Product",
    },
  ],
};
export default data;
